apiVersion: v1
kind: Pod
metadata:
  name: ml-pod
  labels:
    app: ml-app
spec:
  containers:
  - name: podinfo
    image: ghcr.io/sithumonline/octo-py:latest
    ports:
    - containerPort: 80
    env:
    - name: PROMETHEUS_ENDPOINT
      value: http://prometheus.linkerd-viz.svc.cluster.local:9090
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-l
  labels:
    app: ml-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: ml-app

# kubectl -n research run curl-foo --image=radial/busyboxplus:curl -i --tty --rm

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ml-cronjob
  labels:
    app: ml-app
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ml-cronjob
            image: ghcr.io/sithumonline/octo-py:latest
            env:
            - name: PROMETHEUS_ENDPOINT
              value: http://prometheus.linkerd-viz.svc.cluster.local:9090
            command:
            - /bin/sh
            - -c
            - cd /app && poetry run cron
          restartPolicy: OnFailure
