apiVersion: v1
kind: Pod
metadata:
  name: pod-info
  annotations:
    linkerd.io/inject: enabled
spec:
  containers:
  - name: podinfo
    image: stefanprodan/podinfo
    ports:
    - containerPort: 9898
