apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"linkerd.io/created-by":"linkerd/helm stable-2.10.2"},"labels":{"component":"prometheus","linkerd.io/extension":"viz","namespace":"linkerd-viz"},"name":"prometheus","namespace":"linkerd-viz"},"spec":{"ports":[{"name":"admin-http","port":9090,"targetPort":9090}],"selector":{"component":"prometheus","linkerd.io/extension":"viz"},"type":"ClusterIP"}}
    linkerd.io/created-by: linkerd/helm stable-2.10.2
  creationTimestamp: "2021-10-14T04:12:19Z"
  labels:
    component: prometheus
    linkerd.io/extension: viz
    namespace: linkerd-viz
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:linkerd.io/created-by: {}
        f:labels:
          .: {}
          f:component: {}
          f:linkerd.io/extension: {}
          f:namespace: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":9090,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:component: {}
          f:linkerd.io/extension: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-10-14T04:12:19Z"
  name: prometheus-expose
  namespace: linkerd-viz
  resourceVersion: "22798353"
  selfLink: /api/v1/namespaces/linkerd-viz/services/prometheus
  uid: 0683f936-a6d6-4a9f-897d-27be0f67df5a
spec:
  # clusterIP: 10.0.219.190
  ports:
  - name: admin-http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    component: prometheus
    linkerd.io/extension: viz
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
