apiVersion: apps/v1
kind: Deployment
metadata:
  name: ts-model
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ts-model-server
  template:
    metadata:
      labels:
        run: ts-model-server
    spec:
      containers:
        - name: octo-guacamole
          image: ghcr.io/sithumonline/octo-py:latest
          env: 
            - name: PROMETHEUS_ENDPOINT
              value: http://prometheus.linkerd-viz.svc.cluster.local:9090
---
apiVersion: v1
kind: Service
metadata:
  name: ts-model-server
  labels:
    run: ts-model-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    run: ts-model-server
